export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CAMPAIGN_REPOSITORY = 'CAMPAIGN_REPOSITORY'
export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY'